name: Test and coverage

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: code-coverage
          fail_ci_if_error: true
          verbose: true
          file: coverage.out
